### ISSUE TITLE
Keyboard Support?

### ISSUE THREAD

**Issue by EDKGames1** [virgesmith/pico-zxspectrum#8]
Is there any way it could support a USB or Ps/2 keyboard? Maybe using a modified keyboard library or something?

**Comment by virgesmith** [comment]
I'm sure you could add something based on e.g.  https://github.com/raspberrypi/pico-examples/tree/master/usb/host/host_cdc_msc_hid. Would obviously need to provide power to the pico either via USB or pins as well
